In [148]:
import pandas as pd
import numpy as np

In [149]:
# carregar a base de dados

df = pd.read_csv('http://www.ppgia.pucpr.br/~jean.barddal/datascience/kobe_shots.csv')

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30697 entries, 0 to 30696
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   action_type         30697 non-null  object
 1   combined_shot_type  30697 non-null  object
 2   game_event_id       30697 non-null  int64
 3   game_id             30697 non-null  int64
 4   lat                 30697 non-null  float64
 5   loc_x               30697 non-null  int64
 6   loc_y               30697 non-null  int64
 7   lon                 30697 non-null  float64
 8   minutes_remaining   30697 non-null  int64
 9   period              30697 non-null  int64
 10  playoffs            30697 non-null  int64
 11  season              30697 non-null  object
 12  seconds_remaining   30697 non-null  int64
 13  shot_distance       30697 non-null  int64
 14  shot_made_flag      25697 non-null  float64
 15  shot_type           30697 non-null  object
 16  shot_zone_area      30697 non-null  object
 17  shot_zone_basic     30697 non-null  object
 18  shot_zone_range     30697 non-null  object
 19  team_id             30697 non-null  int64
 20  team_name           30697 non-null  object
 21  game_date           30697 non-null  object
 22  matchup             30697 non-null  object
 23  opponent            30697 non-null  object
 24  shot_id             30697 non-null  int64
dtypes: float64(3), int64(11), object(11)
memory usage: 5.9+ MB

In [151]:
# obter numero de linhas e colunas -> shape
n_linhas, n_colunas = df.shape
print(n_linhas)
print(n_colunas)

30697
25

In [152]:
# vendo as primeiras 10 linhas do dataset
df.head(10)

         action_type combined_shot_type  ...  opponent  shot_id
0          Jump Shot          Jump Shot  ...       POR        1
1          Jump Shot          Jump Shot  ...       POR        2
2          Jump Shot          Jump Shot  ...       POR        3
3          Jump Shot          Jump Shot  ...       POR        4
4  Driving Dunk Shot               Dunk  ...       POR        5
5          Jump Shot          Jump Shot  ...       POR        6
6         Layup Shot              Layup  ...       POR        7
7          Jump Shot          Jump Shot  ...       POR        8
8          Jump Shot          Jump Shot  ...       POR        9
9  Running Jump Shot          Jump Shot  ...       POR       10

[10 rows x 25 columns]

In [153]:
# final da base de dados 
df.tail(5)

             action_type combined_shot_type  ...  opponent  shot_id
30692          Jump Shot          Jump Shot  ...       IND    30693
30693           Tip Shot           Tip Shot  ...       IND    30694
30694  Running Jump Shot          Jump Shot  ...       IND    30695
30695          Jump Shot          Jump Shot  ...       IND    30696
30696          Jump Shot          Jump Shot  ...       IND    30697

[5 rows x 25 columns]

In [154]:
# selecionando coluna action_type
df['action_type']

0                Jump Shot
1                Jump Shot
2                Jump Shot
3                Jump Shot
4        Driving Dunk Shot
               ...
30692            Jump Shot
30693             Tip Shot
30694    Running Jump Shot
30695            Jump Shot
30696            Jump Shot
Name: action_type, Length: 30697, dtype: object

In [155]:
# selecionando ciluna action_type e period
df[['action_type', 'period']]

             action_type  period
0              Jump Shot       1
1              Jump Shot       1
2              Jump Shot       1
3              Jump Shot       1
4      Driving Dunk Shot       2
...                  ...     ...
30692          Jump Shot       4
30693           Tip Shot       4
30694  Running Jump Shot       4
30695          Jump Shot       4
30696          Jump Shot       4

[30697 rows x 2 columns]

In [156]:
# describe -> nos dá estatísticas para colunas numéricas
df.describe()

       game_event_id       game_id  ...       team_id       shot_id
count   30697.000000  3.069700e+04  ...  3.069700e+04  30697.000000
mean      249.190800  2.476407e+07  ...  1.610613e+09  15349.000000
std       150.003712  7.755175e+06  ...  0.000000e+00   8861.604943
min         2.000000  2.000001e+07  ...  1.610613e+09      1.000000
25%       110.000000  2.050008e+07  ...  1.610613e+09   7675.000000
50%       253.000000  2.090035e+07  ...  1.610613e+09  15349.000000
75%       368.000000  2.960047e+07  ...  1.610613e+09  23023.000000
max       659.000000  4.990009e+07  ...  1.610613e+09  30697.000000

[8 rows x 14 columns]

In [157]:
# Selecionar linhas 
# Exemplo: linhas 10 em linhas 
# de 10 em diante

df[10:]

             action_type combined_shot_type  ...  opponent  shot_id
10             Jump Shot          Jump Shot  ...       POR       11
11             Jump Shot          Jump Shot  ...       UTA       12
12     Running Jump Shot          Jump Shot  ...       UTA       13
13             Jump Shot          Jump Shot  ...       UTA       14
14             Jump Shot          Jump Shot  ...       UTA       15
...                  ...                ...  ...       ...      ...
30692          Jump Shot          Jump Shot  ...       IND    30693
30693           Tip Shot           Tip Shot  ...       IND    30694
30694  Running Jump Shot          Jump Shot  ...       IND    30695
30695          Jump Shot          Jump Shot  ...       IND    30696
30696          Jump Shot          Jump Shot  ...       IND    30697

[30687 rows x 25 columns]

In [158]:
# obtendo linhas 10 a 20

df[10:20]

           action_type combined_shot_type  ...  opponent  shot_id
10           Jump Shot          Jump Shot  ...       POR       11
11           Jump Shot          Jump Shot  ...       UTA       12
12   Running Jump Shot          Jump Shot  ...       UTA       13
13           Jump Shot          Jump Shot  ...       UTA       14
14           Jump Shot          Jump Shot  ...       UTA       15
15           Jump Shot          Jump Shot  ...       UTA       16
16  Driving Layup Shot              Layup  ...       UTA       17
17           Jump Shot          Jump Shot  ...       UTA       18
18           Jump Shot          Jump Shot  ...       UTA       19
19  Driving Layup Shot              Layup  ...       UTA       20

[10 rows x 25 columns]

In [159]:
# loc, iloc, ix
# loc -> faz seleção de intâncias de acordo com a índice
# iloc -> faz seleçãp de instancias, mas por posição
# ix -> faz os dois (deprecated)

In [160]:
df.loc[0]

action_type                    Jump Shot
combined_shot_type             Jump Shot
game_event_id                         10
game_id                         20000012
lat                              33.9723
loc_x                                167
loc_y                                 72
lon                             -118.103
minutes_remaining                     10
period                                 1
playoffs                               0
season                           2000-01
seconds_remaining                     27
shot_distance                         18
shot_made_flag                       NaN
shot_type                 2PT Field Goal
shot_zone_area             Right Side(R)
shot_zone_basic                Mid-Range
shot_zone_range                16-24 ft.
team_id                       1610612747
team_name             Los Angeles Lakers
game_date                     2000-10-31
matchup                        LAL @ POR
opponent                             POR
shot_id                                1
Name: 0, dtype: object

In [161]:
df.iloc[0]

action_type                    Jump Shot
combined_shot_type             Jump Shot
game_event_id                         10
game_id                         20000012
lat                              33.9723
loc_x                                167
loc_y                                 72
lon                             -118.103
minutes_remaining                     10
period                                 1
playoffs                               0
season                           2000-01
seconds_remaining                     27
shot_distance                         18
shot_made_flag                       NaN
shot_type                 2PT Field Goal
shot_zone_area             Right Side(R)
shot_zone_basic                Mid-Range
shot_zone_range                16-24 ft.
team_id                       1610612747
team_name             Los Angeles Lakers
game_date                     2000-10-31
matchup                        LAL @ POR
opponent                             POR
shot_id                                1
Name: 0, dtype: object

In [162]:
# apagando a primeira linha
#df.drop(0, axis=0, inplace=True).reset_index()  -> cria um novo indice a partir do 0
df.drop(0, axis=0, inplace=True) # axis = 0 -> remove linha

In [163]:
#df.loc[0]

In [164]:
df.iloc[0]

action_type                    Jump Shot
combined_shot_type             Jump Shot
game_event_id                         12
game_id                         20000012
lat                              34.0443
loc_x                               -157
loc_y                                  0
lon                             -118.427
minutes_remaining                     10
period                                 1
playoffs                               0
season                           2000-01
seconds_remaining                     22
shot_distance                         15
shot_made_flag                         0
shot_type                 2PT Field Goal
shot_zone_area              Left Side(L)
shot_zone_basic                Mid-Range
shot_zone_range                 8-16 ft.
team_id                       1610612747
team_name             Los Angeles Lakers
game_date                     2000-10-31
matchup                        LAL @ POR
opponent                             POR
shot_id                                2
Name: 1, dtype: object

In [165]:
# Analisando coluna "shot_type"

In [166]:
# valor possíveis da coluna "shot_type"
df['shot_type'].unique()

array(['2PT Field Goal', '3PT Field Goal'], dtype=object)

In [167]:
# Quantidade de valores únicos
df['shot_type'].nunique()

2

In [168]:
# Contagem de linhas por valor possível de shot_type
df['shot_type'].value_counts()

2PT Field Goal    24270
3PT Field Goal     6426
Name: shot_type, dtype: int64

In [169]:
# Group by + count 
df.groupby('shot_type').count().max(axis=1)

shot_type
2PT Field Goal    24270
3PT Field Goal     6426
dtype: int64

In [170]:
# contagem das linhas por shot_type usando filtros
# Selecionar instancias cujo calor de shot_typ seja 2PT
# Selecionar instancias cujo valor de shot_type 3PT
# Contar ambas :)
df_2pt = df[df['shot_type'] == '2PT Field Goal']
df_3pt = df[df['shot_type'] == '3PT Field Goal']

In [171]:
#df['shot_type'] == '2PT Field Goal'

In [172]:
len(df_2pt)

24270

In [173]:
len(df_3pt)

6426

In [174]:
# Número de linhas que representam arremessos de 2pt e que foram certos (shot_made_flag = 1.0/0.0)
# & = E
# | = ou
# ~ = não
mask = (df['shot_type'] == '2PT Field Goal') & (df['shot_made_flag'] == 1.0)
len(df[mask])

9683

In [175]:
# max, min, mean, std, var
df['minutes_remaining'].max()

11

In [176]:
df['minutes_remaining'].min()

0

In [177]:
df['minutes_remaining'].mean()

4.885457388584832

In [178]:
df['minutes_remaining'].std()

3.449830165385689

In [179]:
df['minutes_remaining'].var()

11.90132817000505

In [180]:
# mediana
np.median(df['minutes_remaining'])

5.0

In [181]:
# moda = ?

In [182]:
# soma
df['minutes_remaining'].sum()

149964

In [183]:
# Verificação de valoresfaltantes -> isna ou isnull
df.isna().sum()

action_type              0
combined_shot_type       0
game_event_id            0
game_id                  0
lat                      0
loc_x                    0
loc_y                    0
lon                      0
minutes_remaining        0
period                   0
playoffs                 0
season                   0
seconds_remaining        0
shot_distance            0
shot_made_flag        4999
shot_type                0
shot_zone_area           0
shot_zone_basic          0
shot_zone_range          0
team_id                  0
team_name                0
game_date                0
matchup                  0
opponent                 0
shot_id                  0
dtype: int64

In [184]:
# ordenação -> sort_values()
#df.sort_values('period', ascending=False)#, inplace = True)
# ordenando por loc_x e loc_y

df.sort_values(['loc_x', 'loc_y'])

               action_type combined_shot_type  ...  opponent  shot_id
22383  Step Back Jump shot          Jump Shot  ...       SAS    22384
19552            Jump Shot          Jump Shot  ...       PHX    19553
21801            Jump Shot          Jump Shot  ...       MIN    21802
21120            Jump Shot          Jump Shot  ...       LAC    21121
15475            Jump Shot          Jump Shot  ...       CLE    15476
...                    ...                ...  ...       ...      ...
5507             Jump Shot          Jump Shot  ...       LAC     5508
11883            Jump Shot          Jump Shot  ...       GSW    11884
12176            Jump Shot          Jump Shot  ...       MEM    12177
9244             Jump Shot          Jump Shot  ...       MIN     9245
9616             Jump Shot          Jump Shot  ...       GSW     9617

[30696 rows x 25 columns]

In [185]:
# Criando de novas colunas (a partir de colunas existentes)
# Criando nova coluna a partir de game_event_id que será o valor original somando de 50
df['game_event_id_somando'] = df['game_event_id']  + 50

In [186]:
def is_home_game(x): # valor de cada linha da coluna marchup
  if x.find('@') < 0: 
    return 1
  else: 
    return 0

# aplicar a função em cada valor da coluna matchup
df['home_game'] = df['matchup'].apply(is_home_game)

In [187]:
# usando apply com lambda
df['home_game_lambda'] = df['matchup'].apply(lambda x: 1 if (x.find('@') < 0) else 0)

In [188]:
df

             action_type combined_shot_type  ...  home_game  home_game_lambda
1              Jump Shot          Jump Shot  ...          0                 0
2              Jump Shot          Jump Shot  ...          0                 0
3              Jump Shot          Jump Shot  ...          0                 0
4      Driving Dunk Shot               Dunk  ...          0                 0
5              Jump Shot          Jump Shot  ...          0                 0
...                  ...                ...  ...        ...               ...
30692          Jump Shot          Jump Shot  ...          1                 1
30693           Tip Shot           Tip Shot  ...          1                 1
30694  Running Jump Shot          Jump Shot  ...          1                 1
30695          Jump Shot          Jump Shot  ...          1                 1
30696          Jump Shot          Jump Shot  ...          1                 1

[30696 rows x 28 columns]

In [190]:
# A partir de game_date, inferir anom mes, dia, dia da semana, e dia do ano
df['game_date'] = pd.to_datetime(df['game_date']) # sobrescrevendo a coluna original após conversao para tupo de data
df['ano'] = df['game_date'].dt.year
df['mes'] = df['game_date'].dt.month
df['dia'] = df['game_date'].dt.day
df['dia_da_semana'] = df['game_date'].dt.dayofweek
df['dia_do_ano'] = df['game_date'].dt.dayofyear 
df

             action_type combined_shot_type  ...  dia_da_semana  dia_do_ano
1              Jump Shot          Jump Shot  ...              1         305
2              Jump Shot          Jump Shot  ...              1         305
3              Jump Shot          Jump Shot  ...              1         305
4      Driving Dunk Shot               Dunk  ...              1         305
5              Jump Shot          Jump Shot  ...              1         305
...                  ...                ...  ...            ...         ...
30692          Jump Shot          Jump Shot  ...              0         171
30693           Tip Shot           Tip Shot  ...              0         171
30694  Running Jump Shot          Jump Shot  ...              0         171
30695          Jump Shot          Jump Shot  ...              0         171
30696          Jump Shot          Jump Shot  ...              0         171

[30696 rows x 33 columns]

In [191]:
# Trasnpor -> pesquisam sobre como o pandas conseguem transpor dados tão rapidamente
df.T

                                     1      ...                  30696
action_type                      Jump Shot  ...              Jump Shot
combined_shot_type               Jump Shot  ...              Jump Shot
game_event_id                           12  ...                    471
game_id                           20000012  ...               49900088
lat                                34.0443  ...                33.9723
loc_x                                 -157  ...                      1
loc_y                                    0  ...                     72
lon                               -118.427  ...               -118.269
minutes_remaining                       10  ...                      0
period                                   1  ...                      4
playoffs                                 0  ...                      1
season                             2000-01  ...                1999-00
seconds_remaining                       22  ...                     39
shot_distance                           15  ...                      7
shot_made_flag                           0  ...                      0
shot_type                   2PT Field Goal  ...         2PT Field Goal
shot_zone_area                Left Side(L)  ...              Center(C)
shot_zone_basic                  Mid-Range  ...  In The Paint (Non-RA)
shot_zone_range                   8-16 ft.  ...        Less Than 8 ft.
team_id                         1610612747  ...             1610612747
team_name               Los Angeles Lakers  ...     Los Angeles Lakers
game_date              2000-10-31 00:00:00  ...    2000-06-19 00:00:00
matchup                          LAL @ POR  ...            LAL vs. IND
opponent                               POR  ...                    IND
shot_id                                  2  ...                  30697
game_event_id_somando                   62  ...                    521
home_game                                0  ...                      1
home_game_lambda                         0  ...                      1
ano                                   2000  ...                   2000
mes                                     10  ...                      6
dia                                     31  ...                     19
dia_da_semana                            1  ...                      0
dia_do_ano                             305  ...                    171

[33 rows x 30696 columns]